%% Example: lagged 2D GCMI for one epoched dyad
%
% EEG_A.data and EEG_B.data must be arranged as:
% channels x samples x paired trials.
%
% The input should already be filtered into the frequency band of interest.

outputFile = 'dyad_lagged_gcmi.mat';

results = lagged_gcmi_dyad( ...
    EEG_A.data, ...
    EEG_B.data, ...
    EEG_A.srate, ...
    'LagsMs', -500:50:500, ...
    'NumSurrogates', 19, ...
    'RandomSeed', 1, ...
    'ChannelLabelsA', {EEG_A.chanlocs.labels}, ...
    'ChannelLabelsB', {EEG_B.chanlocs.labels}, ...
    'UseParallel', false, ...
    'OutputFile', outputFile);

% Main output dimensions:
size(results.gcmiObserved)
size(results.gcmiSurrogates)

% Actual lags may differ slightly from the requested values when the
% sampling rate cannot represent exact 50-ms increments.
disp(table( ...
    results.requestedLagsMilliseconds(:), ...
    results.lagsSamples(:), ...
    results.lagsMilliseconds(:), ...
    'VariableNames', { ...
        'RequestedLagMs', ...
        'LagSamples', ...
        'ActualLagMs'}));
